config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "items#index"

  resources :items, except: :index do
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: :destroy

  resources :bookings, only: [:new, :create, :destroy, :index, :show]

  get "my-items", to: "pages#my_items", as: :my_items
  get "user-items", to: "pages#user_items", as: :user_items
  get "my-account", to: "pages#my_account", as: :my_account
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates :end_date, comparison: { greater_than: :start_date }
  validates :user_id, :item_id, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  CATEGORIES = ["Outdoor Adventure", "Water Sports", "Winter Sports", "Team Sports", "Fitness & Training", "Cycling", "Recreational Sports", "Extreme Sports"]
  validates :title, :description, :price, :category, :location, presence: true
  validates :category, inclusion: { in: CATEGORIES }

  include PgSearch::Model
  pg_search_scope :search_by_title_and_category_and_location,
    against: [ :title, :category, :location, :description],
  using: {
    tsearch: { prefix: true }
  }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates :comments, :rating, presence: true
  validates :comments, length: { maximum: 500 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :items
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email, :username, :first_name, :last_name, presence: true

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])

     # For additional in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_booking, only: [:destroy, :show]

  def index
    @bookings = Booking.where(user_id: params[:user_id]).order(created_at: :desc)
  end

  def new
    @booking = Booking.new
  end

  def show
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user_id = current_user.id
    if @booking.save
      redirect_to booking_path(@booking)
    else
      @item = Item.find(@booking.item.id)
      @item_id = @item.id
      @review = Review.new(item_id: @item_id)
      @reviews = Review.where(item_id: @item.id)
      render "items/show", status: :unprocessable_entity
    end
  end

  def destroy
    @booking.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :total_price, :item_id)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    if params[:category].present?
      @items = Item.where(category: params[:category])
    else
      @items = Item.all
      if params[:search].present?
        @items = Item.search_by_title_and_category_and_location(params[:search])
      else
        @items = Item.all
      end
    end
    @items = @items.page(params[:page]).per(12)
    @markers = @items.geocoded.map do |item|
      {
        lat: item.latitude,
        lng: item.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {item: item})
      }
    end
  end

  def show
    @item_id = params[:item_id]
    @booking = Booking.new(item_id: @item_id)
    @review = Review.new(item_id: @item_id)
    @reviews = Review.where(item_id: @item.id)
    @markers = [{
        lat: @item.latitude,
        lng: @item.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {item: @item})
      }]
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    if @item.save
      redirect_to my_items_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @item.update(item_params)
    if @item.save
      redirect_to my_items_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @item.destroy
    redirect_to my_items_path, status: :see_other
  end

  private

  def item_params
    params.require(:item).permit(:title, :description, :price, :category, :location, :image)
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def my_items
    if current_user
      @items = current_user.items.order(created_at: :desc)
    else
      redirect_to new_user_session_path
    end
  end

  def user_items
    @user = User.find(params[:user_id])
    @items = @user.items
  end

  def my_account
    if !current_user
      redirect_to new_user_session_path
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @item = Item.find(params[:item_id])
    if !current_user
      redirect_to item_path(@item), notice: "Please login first"
      return
    end
    @review = Review.new(review_params)
    @review.item = @item
    @review.user = current_user
    if @review.save
      redirect_to item_path(@item)
    else
      redirect_to item_path(@item), alert: "Couldn't create review"
    end
  end

  def destroy
    @review = Review.find(params[:id])
    item = @review.item
    @review.destroy
    redirect_to item_path(item)
  end

  private

  def review_params
    params.require(:review).permit(:comments, :rating, :item_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_new.html.erb
<h2>Book this item</h2>
<div data-controller="total-price" data-total-price-price-per-day-value="<%= @item.price %>">
  Price per day: $<%= @item.price %></strong>
  <%= simple_form_for @booking, url: bookings_path do |f| %>
    <%= f.hidden_field :item_id, value: @item.id %>
    <%= f.hidden_field :total_price, { data: { total_price_target: "result" } }%>

    <%= f.input :start_date, as: :string, input_html: { data: { controller: "datepicker", total_price_target: "startDate", action: "change->total-price#sum"} } %>
    <%= f.input :end_date, as: :string, input_html: { data: { controller: "datepicker", total_price_target: "endDate", action: "change->total-price#sum" } } %>
    <strong><p data-total-price-target="totalPrice" class="d-none"></p></strong>
    <%= f.submit "Book this item", data: { "total-price-target": "SubmitButton" }, class: "buttons" %>
  <% end %>
</div>

app/views/bookings/index.html.erb
<div class="d-flex justify-content-center">
  <div class="container">
    <% if @bookings.present? %>
      <h1 class="text-center mb-3">You've booked <%= @bookings.count %><%= @bookings.count > 1 ? " items" : " item" %> so far!</h1>
      <div class="row">
        <% @bookings.each do |booking| %>
          <div class="col-12 mb-3 d-flex justify-content-around">
            <div class="card" style="width: 40%;">
              <div class="row g-0">
                <div class="col-md-4">
                  <% if booking.item.image.attached? %>
                    <div class="card-img-top" style="height: 180px; overflow: hidden;">
                      <%= cl_image_tag booking.item.image.key, class: "img-fluid", style: "height: 100%; width: 100%; object-fit: cover;" %>
                    </div>
                  <% else %>
                    <div class="card-img-top" style="height: 180px; background-color: #f8f9fa; display: flex; justify-content: center; align-items: center;">
                      <p>Default image</p>
                    </div>
                  <% end %>
                </div>
                <div class="col-md-8">
                  <div class="card-body">
                    <h5 class="card-title"><strong><%= booking.item.title %></strong></h5>
                    <p class="card-text"><strong>From: </strong><%= booking.start_date %> To: <%= booking.end_date %></p>
                    <p class="card-text"><small class="text-muted">Booked on: <%= booking.created_at %></small></p>
                    <div class="d-flex justify-content-between">
                      <p><%= link_to "View full details", booking_path(booking), class: "buttons" %></p>
                      <p><%= link_to "Book again", item_path(id: booking.item), class: "buttons" %></p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <% if booking.item.reviews.none? { |review| review.user_id == current_user.id } %>
              <div class="alert alert-warning" role="alert">
                Had a winning experience with Gear Up Rentals? Don't forget to <%= link_to "share your review", item_path(id: booking.item)  %>!
                <%=  %>
              </div>
            <% end %>
        <% end %>
      </div>
    <% else %>
      <h1 class="text-center">You haven't booked any item yet...</h1>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <div class="text-center" >
    <i class="fa-solid fa-circle-check fa-2xl" style="color: #418605;"></i>
    <strong><h1 style="color: #3E8302">Hey, <%= @booking.user.first_name %>! You successfully booked an item!</h1></strong>
  </div>


    <div class="row justify-content-center my-5">
      <div class="col-12 col-lg-6 border rounded shadow py-3 px-4">
        <h3 class="pt-4 text-center">Booking details:</h3>
        <% if @booking.item.image.attached? %>
                    <div class="card-img-top" style="overflow: hidden;">
                      <%= cl_image_tag @booking.item.image.key, class: "img-fluid", style: "height: 350px; width: 100%; object-fit: cover;" %>
                    </div>
                  <% else %>
                    <div class="card-img-top" style="height: 180px; background-color: #f8f9fa; display: flex; justify-content: center; align-items: center;">
                      <p>Default image</p>
                    </div>
                  <% end %>
        <p class="ps-2 pt-3"><strong>Item: </strong><%= @booking.item.title %></p>
        <p class="ps-2"><strong>Description: </strong><%= @booking.item.description %></p>
        <p><i class="fa-solid fa-location-dot fa-lg ps-2" style="color: #044c3c;"></i><strong>Pick-up location: </strong><%= @booking.item.location %></p>
        <p><i class="fa-solid fa-user fa-lg ps-2" style="color: #044c3c;"></i><strong>Item owner: </strong><%= @booking.item.user.first_name %> <%= @booking.item.user.last_name %></p>

        <div class="text-center">
          <p> Your booking starts on <strong><%= @booking.start_date %></strong> and ends on <strong><%= @booking.end_date %></strong></p>
          <p><strong>Total price: </strong>$<%= @booking.total_price %></p>
        </div>

        <h4 class="text-center py-3"><%=link_to "Check all your bookings", bookings_path(user_id: @booking.user_id ), class: "buttons" %>
        <%# <<%= link_to "Edit booking details", item_path()%>
      </div>
    </div>
  </div>
</div>

app/views/items/_info_window.html.erb
<div class="mapboxgl-pop">
  <h4><%= item.title %></h4>
    <% if item.image.key.present? %>
    <%= link_to item_path(item.id) do %>
    <%= cl_image_tag item.image.key, class: "img-fluid" %>
    <% end %>
    <% else %>
      <p>No image available</p>
    <% end %>
  <h6>Location: <%= item.location %></h6>
  <h6>Price: $<%= item.price %> per day</h6>
</div>

app/views/items/edit.html.erb
<div class="container min-vh-100 d-flex flex-column justify-content-center align-items-center">
  <h1 class="text-center">Edit your item</h1>

  <div class="form container mx-3 col-12 col-sm-4 shadow-lg p-5">
    <!-- Your form content -->
    <%= simple_form_for @item do |f| %>
      <%= f.input :title, placeholder:"Add a descriptive title" %>
      <%= f.input :price %>
      <%= f.input :image, as: :file,  input_html: { multiple: false } %>
      <%= f.input :description, placeholder:"Add a description" %>
      <%= f.input :category, as: :select, collection: Item::CATEGORIES, prompt: "Select category" %>
      <%= f.input :location %>

      <div class="d-flex justify-content-center pb-1">
        <%= f.submit "Submit", class: "buttons" %>
      </div>
    <% end %>
  </div>
</div>

app/views/items/index.html.erb
<% unless params[:category].present? || params[:page].present? %>
  <%= render "shared/banner" %>
<% end %>
<div class="d-flex justify-content-center">
  <div class="container">
    <div class="cards">

    <% if @items.present? %>
      <% @items.each do |item| %>
        <%= link_to item_path(item) do %>
          <div class="card border" style="width: 18rem;">
            <% if item.image.attached? %>
              <div class="card-img-top rounded-4" style="height: 180px; overflow: hidden;">
                <%= cl_image_tag item.image.key, class: "img-fluid", style: "height: 100%; width: 100%; object-fit: cover;" %>
              </div>
            <% else %>
              <div class="card-img-top" style="height: 180px; background-color: #f8f9fa; display: flex; justify-content: center; align-items: center;">
                <p>Default image</p>
              </div>
            <% end %>

            <div class="card-body ">
              <h5 class="card-title"><%= item.title.capitalize %></h5>
              <h6 class="card-subtitle mb-2 text-muted"><%= item.category %></h6>
              <p class="card-text"><strong>$<%= item.price %></strong> per day</p>
              <%# <%= link_to "View details", item_path(item), class: "buttons"%>
              <p class="buttons">View Details</p>
            </div>
          </div>
        <% end %>
      <% end %>

    <% else %>
      <p>"Sorry, no item available"</p>
      <% end %>

    </div>
  </div>
</div>


<div class="d-flex justify-content-center mt-5">
  <div class="w-50 text-center">
  <%= paginate @items %>
  </div>
</div>

<div data-controller="toogle">
  <div class="d-flex justify-content-center">
    <button type="button" class="btn btn-outline-dark mt-5 mb-3" data-action="click->toogle#hide" data-toogle-target="button">Show map</button>
  </div>
  <div class="mt-5">
    <div class="invisible" data-toogle-target="Map">
      <%= render "shared/map" %>
    </div>
  </div>

</div>

<%# <%= link_to "See details", item_path(item) %>

app/views/items/new.html.erb
<div class="container min-vh-100 d-flex flex-column justify-content-center align-items-center">
  <h1 class="text-center">Rent out an item</h1>

  <div class="form container mx-3 col-12 col-sm-4 shadow-lg p-5">
    <!-- Your form content -->
    <%= simple_form_for @item do |f| %>
      <%= f.input :title, placeholder:"Add a descriptive title" %>
      <%= f.input :price %>
      <%= f.input :image, as: :file,  input_html: { multiple: false } %>
      <%= f.input :description, placeholder:"Add a description" %>
      <%= f.input :category, as: :select, collection: Item::CATEGORIES, prompt: "Select category" %>
      <%= f.input :location %>

      <div class="d-flex justify-content-center pb-1">
        <%= f.submit "Submit", class: "buttons" %>
      </div>
    <% end %>
  </div>
</div>

app/views/items/show.html.erb
<div class="container">
  <h1><%= @item.title %></h1>
  <div class="row">
    <!-- Details Section -->
    <div class="col-md-8 details">
      <div>

        <p><% if @item.image.attached? %>
          <%= cl_image_tag @item.image.key, style: "height: 600px; width: 100%; object-fit: cover;" %>
        <% end %>
      </div></p>
      <div class="card">
      <div class="card-header">
        <strong><i class="fa-regular fa-user"></i> Renter: </strong><%= link_to @item.user.username, user_items_path(user_id: @item.user.id) %>
      </div>
    <div class="card-body">
      <h5 class="card-title"><strong>Item details: </strong></h5>
      <p class="card-text"><%= @item.description %></p>
      <p class="card-text"><strong><i class="fa-solid fa-location-dot"></i> Pick-up location: </strong><%= @item.location %></p>
    </div>
</div>

    </div>

    <!-- Booking and Mapping Section -->
    <div class="col-md-4">
      <div class="booking mb-4">
        <% if current_user %>
          <%= render "bookings/new" %>
        <% else %>
          <h2>Get ready to gear up!</h2>
          <%= link_to "Sign in to book this item", user_session_path %>
        <% end %>
      </div>
      <div class="mapping">
        <%= render "shared/map" %>
      </div>
    </div>
  </div>

  <!-- Reviews Section -->
  <div class="col-md-8">
    <h3 class="mt-3">Reviews (<%= @item.reviews.count %>):</h3>
    <div class="mb-5">
      <%= render "reviews/reviews" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GearUpRentals</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/categories" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/item.html.erb
<h1>Show pape for now</h1>

<%# <div class="card-category text-white text-center p-4 rounded shadow"
  style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)),
  url(<%= @item.photo.attached? ? url_for(@item.photo.key) : asset_path('Photo_missing_default.jpg') %>);
  <%# background-size: cover;
  background-position: center;
  height: 250px;" %>
  >
<%# <h1><%= @item.name</h1> %>
<%# </div> %> %> %>

app/views/pages/my_account.html.erb
<h1>Hello, <%= current_user.full_name %></h1>

app/views/pages/my_items.html.erb
<div class="d-flex justify-content-center">
  <div class="container">
    <h1 class="text-center">You have a total of <%= @items.count %> items listed!</h1>
      <div class="cards d-flex flex-wrap justify-content-center gap-3">
        <% @items.each do |item| %>
          <div class="card" style="width: 18rem;">
            <% if item.image.attached? %>
              <div class="card-img-top" style="height: 180px; overflow: hidden;">
                <%= cl_image_tag item.image.key, class: "img-fluid", style: "height: 100%; width: 100%; object-fit: cover;" %>
              </div>
            <% else %>
              <div class="card-img-top" style="height: 180px; background-color: #f8f9fa; display: flex; justify-content: center; align-items: center;">
                <p>Default image</p>
              </div>
            <% end %>
            <div class="card-body">
              <h5 class="card-title"><strong><%= item.title %></strong></h5>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">Category: <%= item.category %></li>
              <li class="list-group-item">Price per day: $<%= item.price %></li>
              <li class="list-group-item">Pick-up location: <%= item.location %></li>
            </ul>
            <div class="card-body d-flex justify-content-between">
              <%= link_to edit_item_path(item), class: "buttons" do %>
                <i class="fa-solid fa-pen-to-square"></i> Edit item
              <% end %>
              <%= link_to item_path(item), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "buttons" do %>
                <i class="fa-solid fa-trash"></i> Delete item
              <% end %>
            </div>
            <div class="d-flex justify-content-around mb-3">
              <p class="card-text"><small class="text-muted">Times rented: <%= item.bookings.count %></small></p>
            </div>
          </div>
        <% end %>
      </div>
  </div>
</div>

app/views/pages/user_items.html.erb
<div class="d-flex justify-content-center">
  <div class="container">
    <h1 class="text-center"><%= @user.full_name %> has <%= @items.count %> <%= @items.count > 1 ? "items" : "item" %> listed</h1>
    <div class="cards">
      <% if @items.present? %>
        <% @items.each do |item| %>
          <div class="card" style="width: 18rem;">
            <% if item.image.attached? %>
              <div class="card-img-top" style="height: 180px; overflow: hidden;">
                <%= cl_image_tag item.image.key, class: "img-fluid", style: "height: 100%; width: 100%; object-fit: cover;" %>
              </div>
              <% else %>
                <div class="card-img-top" style="height: 180px; background-color: #f8f9fa; display: flex; justify-content: center; align-items: center;">
                  <p>Default image</p>
                </div>
            <% end %>
            <div class="card-body">
              <h5 class="card-title"><%= item.title %></h5>
              <h6 class="card-subtitle mb-2 text-muted"><%= item.category %></h6>
              <p class="card-text">$<%= item.price %> per day</p>
              <%= link_to "View details", item_path(item) %>
            </div>
          </div>
        <% end %>
      <% else %>
        <p class="text-center">Sorry... No items available</p>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/_reviews.html.erb
<!-- review Section -->

<!-- show existing reviews section -->
<div class="reviewbigcontainer">
  <ul>
    <% @reviews.each do |review| %>
      <li>
        <div class="card">
          <div class="card-header">
            <% review.rating.times do %>
              <i class="fa-solid fa-star"></i>
            <% end %>
            <% (5 - review.rating).times do %>
              <i class="fa-regular fa-star"></i>
            <% end %>
          </div>
          <div class="card-body">
            <blockquote class="blockquote mb-0">
              <p><%= review.comments %></p>
              <footer class="blockquote-footer"><%= review.user.username %>
              <p><cite title="Source Title">Published on <%= review.created_at.strftime("%d/%m/%Y") %></cite></p></footer>
            </blockquote>
          </div>
          <% if current_user && review.user_id == current_user.id %>
            <%= link_to review_path(review), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "delete text-decoration-none" do %>
                <i class="fa-solid fa-trash"></i> Delete review
            <% end %>
          <% end %>

        </div>
      </li>
    <% end %>
  </ul>
</div>

<!-- review Section -->
<!-- add new review Section -->

<% if current_user %>
  <% if @item.bookings.any? { |booking| booking.user_id == current_user.id } %>
    <% if @item.reviews.any? { |review| review.user_id == current_user.id } %>
      <div class="alert alert-success" role="alert">
        We've got your review! Keep gearing up like a pro.
      </div>
    <% else %>
      <%= simple_form_for [@item, @review] do |f| %>
        <%= f.input :comments, class: "reviewbox" %>
        <p>Rating
          <%= f.select :rating, options_for_select([1, 2, 3, 4, 5], @review.rating), class: "rating-dropdown" %>
        </p>
        <%= f.submit class: "buttons" %>
      <% end %>
    <% end %>
  <% else %>
    <div class="alert alert-warning" role="alert">
      You haven't booked this item yet—book now and share your review later!
    </div>
  <% end %>
<% end %>

app/views/shared/_map.html.erb
<div class= "col-lg-11 border-secondary" style="height: 500px; width: 100%"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>

app/views/shared/_navbar.html.erb
<section class="navbar-white py-4">
  <div class="container">
    <%# <nav class="navbar navbar-expand border-bottom d-flex justify-content-between"><i class="fa-solid fa-user"></i>
    </nav> %>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <a class="navbar-brand" href="/">
        <%= image_tag "GMU.png", alt: "Logo Description"%>
      </a>

      <form novalidate="novalidate" class="simple_form search" action="/" accept-charset="UTF-8" method="get">
        <div class="search-form-control form-group">
          <input class="form-control string required" type="text" name="search" id="search" placeholder="Search..." />
          <button name="button" type="submit" class="btn btn-flat search-icon-button">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </form>

      <div class="d-flex">
        <div class="m-3">
          <%= link_to "Rent out an item", new_item_path %>
        </div>
        <% if current_user %>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
              <li class="nav-item dropdown">
                <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://i.pinimg.com/236x/59/a9/2f/59a92f5177c56974e1127977f3b603d1.jpg" />
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                  <%= link_to "My bookings", bookings_path(user_id: current_user.id ), class: "dropdown-item" %>
                  <%= link_to "My items", my_items_path, class: "dropdown-item" %>
                  <%= link_to "Edit details", edit_user_registration_path, class: "dropdown-item" %>
                  <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: "delete"}, class: "dropdown-item"%>
                </div>
              </li>
              <!--li class="nav-item"-->
              <!--/li-->
          <% else %>
            <div class="m-3">
              <%= link_to "Sign in", user_session_path %>
            </div>
          <% end  %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/shared/_reviews.html.erb
    <!-- review Section -->

    <!-- show existing reviews section  -->
    <div class="reviewbigcontainer">
       <ul>
        <% @reviews.each do |review| %>
        <li>
          <div class="container reviewbox border ">
          <p><strong>Username:</strong>
          <%= review.user.username%>
          </p>
          <p><strong>Rating:</strong>
          <%= review.rating%>
          </p>
          <p><strong>Review:</strong>
          <%= review.comments%>
          <% if current_user && review.user_id == current_user.id%>
          <%=  link_to "🗑️ Delete", item_review_path(review), class: "delete",
         data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
       </p>
          <% end %>
          <% end %>
          </div>
        </li>
       </ul>
    </div>


<!-- review Section -->
<!-- add new review Section -->

<div>
  <%if current_user%>
<%= simple_form_for [@item, @review] do |f| %>
  <%= f.input :comments, class: "reviewbox" %>
  <p>Rating
  <%= f.select :rating, options_for_select([1, 2, 3, 4, 5], @review.rating), class: "rating-dropdown" %>
  </p>
  <%= f.submit class: "reviewbox" %>
<% end %>
<% end %>
</div>